-- ============================================================
-- Olist E-Commerce Analysis
-- 06 - Repeat Customers
-- ============================================================
-- Purpose:
-- Investigate repeat purchasing and customer retention across
-- time, geography, and revenue.
-- ============================================================


-- ============================================================
-- 1. Overall Repeat Customer Rate
-- ============================================================
-- What percentage of customers are repeat customers?



-- ============================================================
-- 2. Repeat Customer Rate by Month
-- ============================================================
-- How does the repeat customer rate change over time?



-- ============================================================
-- 3. Repeat Customer Rate by State
-- ============================================================
-- How does repeat purchasing vary across Brazilian states?


-- ============================================================
-- 4. Highest and Lowest Repeat Customer Rates
-- ============================================================
-- Which states have the highest and lowest repeat customer rates?



-- ============================================================
-- 5. Revenue from Repeat Customers
-- ============================================================
-- How much revenue is generated by repeat customers?



-- ============================================================
-- 6. Orders from Repeat Customers
-- ============================================================
-- How many orders are generated by repeat customers?


