-- ============================================================
-- Olist E-Commerce Analysis
-- 06 - Repeat Customers
-- ============================================================
-- Purpose:
-- Investigate repeat purchasing and customer retention across
-- time, geography, and revenue.
-- ============================================================


-- ============================================================
-- 1. Overall Repeat Customer Rate
-- ============================================================

SELECT
ROUND(100.0*COUNT(*)/(SELECT COUNT(DISTINCT customer_unique_id)
FROM customers),2) AS repeat_customer_rate
FROM
(
SELECT
c.customer_unique_id
FROM orders o
JOIN customers c
ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
HAVING COUNT(o.order_id) > 1
) AS repeat_customers;

-- ============================================================
-- 2. Repeat Customer Rate by Month
-- ============================================================
-- How does the repeat customer rate change over time?



-- ============================================================
-- 3. Repeat Customer Rate by State
-- ============================================================
-- How does repeat purchasing vary across Brazilian states?


-- ============================================================
-- 4. Highest and Lowest Repeat Customer Rates
-- ============================================================
-- Which states have the highest and lowest repeat customer rates?



-- ============================================================
-- 5. Revenue from Repeat Customers
-- ============================================================
-- How much revenue is generated by repeat customers?



-- ============================================================
-- 6. Orders from Repeat Customers
-- ============================================================
-- How many orders are generated by repeat customers?


