-- ============================================================
-- Olist E-Commerce Analysis
-- 12 - Customer Ranking
-- ============================================================
-- Purpose:
-- Identify the highest-value customers, product categories,
-- and sellers based on revenue and purchasing activity.
-- ============================================================


-- ============================================================
-- 1. Top 10 Customers by Revenue
-- ============================================================
-- Which unique customers generate the most revenue?


-- ============================================================
-- 2. Top 10 Customers by Order Count
-- ============================================================
-- Which unique customers place the most orders?


-- ============================================================
-- 3. Top 5 Categories by Revenue
-- ============================================================
-- Which product categories generate the most revenue?


-- ============================================================
-- 4. Top 5 Sellers by Revenue
-- ============================================================
-- Which sellers generate the most item revenue?


-- ============================================================
-- 5. Revenue Concentration Among Top Customers
-- ============================================================
-- What percentage of total revenue is generated by the
-- highest-value customers?
