-- ============================================================
-- Olist E-Commerce Analysis
-- 13 - Revenue Concentration
-- ============================================================
-- Purpose:
-- Determine whether revenue is concentrated among a small
-- number of customers, categories, or other segments.
-- ============================================================


-- ============================================================
-- 1. Top 10 Customer Revenue Share
-- ============================================================
-- What percentage of total revenue comes from the top
-- 10 customers?


-- ============================================================
-- 2. Top 100 Customer Revenue Share
-- ============================================================
-- What percentage of total revenue comes from the top
-- 100 customers?


-- ============================================================
-- 3. Repeat Customer Revenue Share
-- ============================================================
-- What percentage of total revenue comes from repeat customers?


-- ============================================================
-- 4. Top Category Revenue Share
-- ============================================================
-- What percentage of total revenue is generated by the
-- highest-revenue product categories?


-- ============================================================
-- 5. Revenue Concentration Assessment
-- ============================================================
-- Determine whether revenue is relatively concentrated among
-- a small number of customers/categories or broadly distributed.
