-- ============================================================
-- Olist E-Commerce Analysis
-- 14 - Repeat Customer Revenue
-- ============================================================
-- Purpose:
-- Connect customer retention to revenue and determine the
-- financial contribution of repeat purchasing.
-- ============================================================


-- ============================================================
-- 1. Revenue from One-Time Customers
-- ============================================================
-- How much revenue is generated by customers who purchased
-- only once?


-- ============================================================
-- 2. Revenue from Repeat Customers
-- ============================================================
-- How much revenue is generated by repeat customers?


-- ============================================================
-- 3. Repeat Customer Revenue Share
-- ============================================================
-- What percentage of total revenue comes from repeat customers?


-- ============================================================
-- 4. Average Revenue per One-Time Customer
-- ============================================================
-- What is the average revenue generated by a one-time customer?


-- ============================================================
-- 5. Average Revenue per Repeat Customer
-- ============================================================
-- What is the average revenue generated by a repeat customer?


-- ============================================================
-- 6. Revenue Generated After the First Purchase
-- ============================================================
-- How much revenue is generated from orders placed after
-- a customer's first purchase?


-- ============================================================
-- 7. Repeat-Customer Revenue by Category
-- ============================================================
-- Which product categories generate the most revenue from
-- repeat customers?
